<?php

namespace CRR\Bundle\DeliveryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryRepository extends EntityRepository
{
    public function getPackageTypes()
    {
        $qb = $this->_em->createQueryBuilder();

        $qb
            ->select('p')
            ->from('CRRPackageBundle:PackageType', 'p')
            ->orderBy('p.sort', 'DESC')
        ;

        return $qb->getQuery()->execute();
    }

    /**
     * @return Delivery
     */
    public function buildDelivery()
    {
        return new Delivery(
            $this->getPackageTypes()
        );
    }
}
